# -*- coding: utf-8 -*-
"""Real_Image_Authenticity_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_OpY5DdKU7ewoNu8r4XbHrz3H8kQB5Z
"""

!unzip dataset.zip

!pip install tensorflow opencv-python pillow

import os
import numpy as np
import cv2
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

img_size = 128

data = []
labels = []

real_path = "dataset/real_img"

for img in os.listdir(real_path):

    img_path = os.path.join(real_path, img)

    image = cv2.imread(img_path)

    image = cv2.resize(image,(img_size,img_size))

    data.append(image)

    labels.append(0)

ai_path = "dataset/ai_img"

for img in os.listdir(ai_path):

    img_path = os.path.join(ai_path, img)

    image = cv2.imread(img_path)

    image = cv2.resize(image,(img_size,img_size))

    data.append(image)

    labels.append(1)

data = np.array(data)
labels = np.array(labels)

print(data.shape)
print(labels.shape)

data = data / 255.0

X_train,X_test,y_train,y_test = train_test_split(
    data,
    labels,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()

model.add(Conv2D(16,(3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(64,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    data,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=25,
    validation_data=(X_test,y_test)
)

loss, accuracy = model.evaluate(X_test,y_test)

print("Test Accuracy:",accuracy)

from sklearn.metrics import confusion_matrix
import numpy as np

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

cm = confusion_matrix(y_test, y_pred)

print(cm)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.legend(["Train","Validation"])

plt.show()

model.save("image_authenticity_model.h5")

model.save("image_authenticity_model.keras")

from tensorflow.keras.models import load_model

model = load_model("image_authenticity_model.keras")

